# Generated by Django 2.1.3 on 2019-02-01 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_colaborador_cargo'),
        ('aluno', '0003_aluno_estado'),
        ('classe', '0012_auto_20190201_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Agendada'), ('2', 'Lecionada'), ('3', 'Cancelada')], default=1, max_length=1)),
                ('unidade', models.CharField(choices=[('1', 'Tres Lagoas'), ('2', 'Agua Clara'), ('3', 'Ribas do Rio Pardo'), ('4', 'Campo Grande')], default=1, max_length=1)),
                ('data_aula', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.sala_aula')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.grupo_aula')),
            ],
        ),
        migrations.CreateModel(
            name='presenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.CharField(choices=[('1', 'Sim'), ('2', 'Nao')], default=2, max_length=1)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='presentes',
            field=models.ManyToManyField(to='aulas.presenca'),
        ),
        migrations.AddField(
            model_name='aula',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.colaborador'),
        ),
    ]
